// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetroHiscore.Api.Data;

#nullable disable

namespace RetroHiscore.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetroHiscore.Api.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConsoleId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Developer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Genre")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageBoxArt")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageIcon")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageIngame")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("AchievementDistributionSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AchievementDistributionHardcoreJson")
                        .HasColumnType("text");

                    b.Property<string>("AchievementDistributionSoftcoreJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AchievementProgressSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaderboardScoresSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MetadataSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RaGameId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RaGameId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.GameSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameSources");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.GameTrackQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RaGameId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RaGameId");

                    b.HasIndex("ResolvedByMemberId");

                    b.HasIndex("Status");

                    b.HasIndex("RaGameId", "Status");

                    b.ToTable("GameTrackQueues");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.Leaderboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GlobalEntryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("GlobalEntryCountSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RaLeaderboardId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RankAsc")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RaLeaderboardId")
                        .IsUnique();

                    b.ToTable("Leaderboards");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FormattedScore")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("FriendRank")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalRank")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeaderboardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ScoreUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("LeaderboardId", "MemberId")
                        .IsUnique();

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.LeaderboardEntrySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FormattedScore")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("FriendRank")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalRank")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeaderboardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("LeaderboardId", "MemberId", "SyncedAt");

                    b.ToTable("LeaderboardEntrySnapshots");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.LeaderboardPopulationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeaderboardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardId", "SyncedAt");

                    b.ToTable("LeaderboardPopulationSnapshots");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("RaApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RaUlid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RaUsername")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RaPresenceGameTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("RaPresenceRaGameId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RaPresenceRichPresenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RaPresenceSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RaStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("RaUsername")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.MemberRaAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateEarned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateEarnedHardcore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("RaAchievementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaAchievementId");

                    b.HasIndex("MemberId", "DateEarned");

                    b.HasIndex("MemberId", "RaAchievementId")
                        .IsUnique();

                    b.ToTable("MemberRaAchievements");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.MemberRaRankSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalRanked")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalSoftcorePoints")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalTruePoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "SyncedAt");

                    b.ToTable("MemberRaRankSnapshots");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.MemberRecentGamePlay", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("RaGameId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsoleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ImageBoxArt")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageIcon")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumAchieved")
                        .HasColumnType("integer");

                    b.Property<int>("NumPossibleAchievements")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MemberId", "RaGameId");

                    b.HasIndex("LastPlayedAt");

                    b.HasIndex("RaGameId");

                    b.ToTable("MemberRecentGamePlays");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.RaAchievement", b =>
                {
                    b.Property<int>("RaAchievementId")
                        .HasColumnType("integer");

                    b.Property<string>("BadgeContentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("BadgeData")
                        .HasColumnType("bytea");

                    b.Property<string>("BadgeName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RaGameId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TrueRatio")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RaAchievementId");

                    b.HasIndex("RaGameId");

                    b.ToTable("RaAchievements");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.RaConsole", b =>
                {
                    b.Property<int>("RaConsoleId")
                        .HasColumnType("integer");

                    b.Property<string>("IconContentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("IconData")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("IconSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RaConsoleId");

                    b.ToTable("Consoles", (string)null);
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.SyncLeaderboardSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ColdIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("HotActivityWindowHours")
                        .HasColumnType("integer");

                    b.Property<int>("HotIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncLeaderboardSettings");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.SyncRecurringJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<int?>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId");

                    b.ToTable("SyncRecurringJobs");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MemberId");

                    b.HasIndex("Kind", "GameId", "StartedAt");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.GameSource", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Game", "Game")
                        .WithMany("Sources")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.GameTrackQueue", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Member", "ResolvedByMember")
                        .WithMany()
                        .HasForeignKey("ResolvedByMemberId");

                    b.Navigation("ResolvedByMember");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.Leaderboard", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Game", "Game")
                        .WithMany("Leaderboards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.LeaderboardEntry", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Leaderboard", "Leaderboard")
                        .WithMany("Entries")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroHiscore.Api.Domain.Member", "Member")
                        .WithMany("Entries")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leaderboard");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.LeaderboardEntrySnapshot", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Leaderboard", "Leaderboard")
                        .WithMany("Snapshots")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroHiscore.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leaderboard");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.LeaderboardPopulationSnapshot", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Leaderboard", "Leaderboard")
                        .WithMany("PopulationSnapshots")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.MemberRaAchievement", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroHiscore.Api.Domain.RaAchievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("RaAchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.MemberRaRankSnapshot", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.MemberRecentGamePlay", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.SyncRun", b =>
                {
                    b.HasOne("RetroHiscore.Api.Domain.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetroHiscore.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.Game", b =>
                {
                    b.Navigation("Leaderboards");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.Leaderboard", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("PopulationSnapshots");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("RetroHiscore.Api.Domain.Member", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
