/* Generated by scripts/generate-api-client.mjs — do not hand-edit types lightly. */
export interface AddGameRequest {
  raGameId: number;
}

export interface PutMemberApiKeyRequest {
  raApiKey: string;
}

export interface PutMemberProfileRequest {
  avatarUrl?: string | null;
}

export interface CurrentMemberDto {
  id: string;
  raUsername?: string | null;
  raUlid?: string | null;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
  hasApiKey: boolean;
  needsOnboarding: boolean;
  isAdmin: boolean;
}

export interface MemberSelfSyncScopeStatusDto {
  lastSyncedAt?: string | null;
  cooldownUntil?: string | null;
}

export interface MemberSelfSyncStatusDto {
  leaderboards: MemberSelfSyncScopeStatusDto;
  profile: MemberSelfSyncScopeStatusDto;
  achievements: MemberSelfSyncScopeStatusDto;
}

export interface MemberSelfSyncLeaderboardsResponse {
  queued: number;
  skippedCooldown: number;
}

export interface MemberSelfSyncRunResponse {
  id: string;
  status: string;
  finishedAt?: string | null;
}

export interface PutMemberRaAccountRequest {
  raUsername: string;
  raApiKey: string;
}

export interface PostAdminMemberInviteRequest {
  discordId: string;
}

export interface PatchAdminMemberIsAdminRequest {
  isAdmin: boolean;
}

export interface AdminMemberInviteDto {
  discordId: string;
  displayName?: string | null;
  hasRaAccount: boolean;
  hasApiKey: boolean;
  isAdmin: boolean;
}

export interface MemberDto {
  id: string;
  raUsername?: string | null;
  raUlid?: string | null;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
  hasApiKey?: boolean;
  raRank?: number | null;
  raTotalRanked?: number | null;
  raTotalPoints?: number | null;
  raTotalSoftcorePoints?: number | null;
  raMetricsSyncedAt?: string | null;
  raRankDelta?: number | null;
  raPointsDelta?: number | null;
  lastActiveAt?: string | null;
  raStatus?: string | null;
  raPresenceRaGameId?: number | null;
  raPresenceGameTitle?: string | null;
  raPresenceIsTracked?: boolean | null;
  raPresenceSyncedAt?: string | null;
}

export interface MembersSummaryDto {
  memberCount: number;
  championshipLeaderDisplayName?: string | null;
  championshipLeaderRaUsername?: string | null;
  championshipLeaderFriendRankOnes?: number | null;
  unlocksLast7Days: number;
  unlocksLast30Days: number;
  activeMembersLast7Days: number;
  lastUnlockAt?: string | null;
  topGameLast7Days?: DashboardAchievementTopGameDto | null;
  playingNowCount: number;
  raMetricsFreshnessAt?: string | null;
}

export interface MemberStandingDto {
  raGameId: number;
  gameTitle: string;
  raLeaderboardId: number;
  leaderboardTitle: string;
  format?: string | null;
  friendRank?: number | null;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  score: number;
  formattedScore: string;
}

export interface MemberRaRankHistoryResponse {
  items: MemberRaRankHistoryItemDto[];
}

export interface MemberRaRankHistoryItemDto {
  syncedAt: string;
  rank?: number | null;
  totalRanked?: number | null;
  totalPoints?: number | null;
  totalTruePoints?: number | null;
  totalSoftcorePoints?: number | null;
}

export interface MemberRaAchievementHistoryResponse {
  items: MemberRaAchievementHistoryItemDto[];
}

export interface MemberRaAchievementHistoryItemDto {
  earnedAt: string;
  pointsEarned: number;
  truePointsEarned: number;
  cumulativeUnlocks: number;
  cumulativePoints: number;
  cumulativeTruePoints: number;
}

export interface MemberRaUnlockedAchievementDto {
  raAchievementId: number;
  title: string;
  description?: string | null;
  points: number;
  badgeUrl?: string | null;
  dateEarned?: string | null;
  hardcoreAchieved: boolean;
}

export interface MemberRaSummaryResponse {
  available: boolean;
  unavailableReason?: string | null;
  summary?: MemberRaSummaryDto | null;
}

export interface MemberRaSummaryDto {
  raUsername: string;
  raUlid?: string | null;
  motto?: string | null;
  userPicUrl?: string | null;
  memberSince?: string | null;
  status?: string | null;
  rank?: number | null;
  totalRanked?: number | null;
  totalPoints?: number | null;
  totalSoftcorePoints?: number | null;
  totalTruePoints?: number | null;
  presence?: MemberRaPresenceGameDto | null;
  recentlyPlayed: MemberRaRecentGameDto[];
  recentAchievements: MemberRaRecentAchievementDto[];
}

export interface MemberRaPresenceGameDto {
  raGameId: number;
  title: string;
  consoleId: number;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  isTracked: boolean;
  richPresenceMsg?: string | null;
  richPresenceAt?: string | null;
  progress?: MemberRaGameProgressDto | null;
  unlockedAchievements: MemberRaUnlockedAchievementDto[];
}

export interface MemberRaRecentGameDto {
  raGameId: number;
  title: string;
  consoleId: number;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  isTracked: boolean;
  lastPlayedAt?: string | null;
  progress?: MemberRaGameProgressDto | null;
  unlockedAchievements: MemberRaUnlockedAchievementDto[];
}

export interface MemberRaGameProgressDto {
  achievementsEarned: number;
  achievementsTotal: number;
  pointsEarned: number;
  pointsPossible?: number | null;
  achievementsEarnedHardcore?: number | null;
  pointsEarnedHardcore?: number | null;
}

export interface MemberRaRecentAchievementDto {
  raAchievementId: number;
  raGameId: number;
  gameTitle: string;
  title: string;
  description?: string | null;
  points: number;
  badgeUrl?: string | null;
  dateAwarded?: string | null;
  hardcoreAchieved: boolean;
  isTracked: boolean;
}

export interface MemberDetailDto {
  id: string;
  raUsername: string;
  raUlid?: string | null;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
  standings: MemberStandingDto[];
}

export interface MemberHistoryItemDto {
  id: string;
  raGameId: number;
  gameTitle: string;
  raLeaderboardId: number;
  leaderboardTitle: string;
  format?: string | null;
  score: number;
  formattedScore: string;
  globalRank?: number | null;
  friendRank?: number | null;
  syncedAt: string;
}

export interface MemberHistoryResponse {
  total: number;
  offset: number;
  limit: number;
  items: MemberHistoryItemDto[];
}

export interface GameDto {
  id: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  leaderboardCount: number;
}

export interface StandingMemberDto {
  id: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
}

export interface FriendStandingDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  score?: number | null;
  formattedScore?: string | null;
  globalRank?: number | null;
  friendRank?: number | null;
  scoreUpdatedAt?: string | null;
}

export interface GameLeaderboardDto {
  id: string;
  raLeaderboardId: number;
  title: string;
  description?: string | null;
  format?: string | null;
  rankAsc: boolean;
  globalEntryCount?: number | null;
  globalEntryCountSyncedAt?: string | null;
  standings: FriendStandingDto[];
}

export interface GameLeaderboardsResponse {
  gameId: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  publisher?: string | null;
  developer?: string | null;
  genre?: string | null;
  releasedAt?: string | null;
  metadataSyncedAt?: string | null;
  leaderboardScoresSyncedAt?: string | null;
  leaderboardSyncStatus: GameLeaderboardSyncStatusDto;
  members: StandingMemberDto[];
  leaderboards: GameLeaderboardDto[];
}

export interface GameHistoryItemDto {
  id: string;
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  raLeaderboardId: number;
  leaderboardTitle: string;
  format?: string | null;
  score: number;
  formattedScore: string;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  friendRank?: number | null;
  syncedAt: string;
}

export interface GameHistoryResponse {
  total: number;
  offset: number;
  limit: number;
  items: GameHistoryItemDto[];
}

export interface LeaderboardPopulationPointDto {
  syncedAt: string;
  entryCount: number;
}

export interface LeaderboardPopulationSeriesDto {
  raLeaderboardId: number;
  title: string;
  points: LeaderboardPopulationPointDto[];
}

export interface GameLeaderboardPopulationHistoryResponse {
  boards: LeaderboardPopulationSeriesDto[];
}

export interface LeaderboardDetailDto {
  id: string;
  raLeaderboardId: number;
  raGameId: number;
  gameTitle: string;
  title: string;
  description?: string | null;
  format?: string | null;
  rankAsc: boolean;
  globalEntryCount?: number | null;
  globalEntryCountSyncedAt?: string | null;
  standings: FriendStandingDto[];
}

export interface LeaderboardHistoryItemDto {
  id: string;
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  score: number;
  formattedScore: string;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  friendRank?: number | null;
  syncedAt: string;
}

export interface LeaderboardHistoryResponse {
  total: number;
  offset: number;
  limit: number;
  items: LeaderboardHistoryItemDto[];
}

export interface SyncAcceptedResponse {
  jobId: string;
}

export interface SyncCooldownResponse {
  message: string;
  availableAt?: string | null;
}

export interface SyncStatusDto {
  id?: string | null;
  trigger?: string | null;
  status?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  error?: string | null;
}

export interface ChampionshipRowDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  friendRankOnes: number;
  boardsWithScore: number;
}

export interface ActivityItemDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  raGameId: number;
  gameTitle: string;
  raLeaderboardId: number;
  leaderboardTitle: string;
  scoreDelta?: number | null;
  friendRankDelta?: number | null;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  globalRankDelta?: number | null;
  formattedScore?: string | null;
}

export interface DashboardGameLeaderDto {
  displayName: string;
  raUsername: string;
  avatarUrl?: string | null;
  friendRankOnes: number;
}

export interface GameLeaderboardSyncStatusDto {
  tier: string;
  groupLastPlayedAt?: string | null;
  leaderboardSyncNextDueAt?: string | null;
  leaderboardSyncIntervalMinutes: number;
  leaderboardSyncIsDue: boolean;
  leaderboardSyncForcedCold: boolean;
}

export interface DashboardGamePlayerAvatarDto {
  displayName: string;
  raUsername: string;
  avatarUrl: string;
}

export interface DashboardGameDto {
  id: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  leaderboardCount: number;
  totalRankedEntriesAcrossBoards?: number | null;
  friendRankOneLeader?: DashboardGameLeaderDto | null;
  playersWithAvatars: DashboardGamePlayerAvatarDto[];
  lastActivityAt?: string | null;
  leaderboardScoresSyncedAt?: string | null;
  totalAchievementsInCatalog?: number | null;
  leaderboardSyncStatus: GameLeaderboardSyncStatusDto;
}

export interface RecentGroupGamePlayerDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  lastPlayedAt: string;
}

export interface RecentGroupGameDto {
  raGameId: number;
  title: string;
  consoleId: number;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  lastPlayedAt: string;
  isTracked: boolean;
  players: RecentGroupGamePlayerDto[];
}

export interface AdminGameTrackQueueItemDto {
  id: string;
  raGameId: number;
  status: number;
  title: string;
  consoleName?: string | null;
  enqueuedAt: string;
  resolvedAt?: string | null;
  failureMessage?: string | null;
}

export interface AdminGameDto {
  id: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  leaderboardCount: number;
  sourceCount: number;
  metadataSyncedAt?: string | null;
  forceColdLeaderboardSync: boolean;
  leaderboardSyncStatus: GameLeaderboardSyncStatusDto;
}

export interface GameSourceDto {
  id: string;
  sourceType: string;
  url: string;
  label?: string | null;
  sortOrder: number;
  note?: string | null;
}

export interface UpsertGameSourceRequest {
  sourceType: string;
  url: string;
  label?: string | null;
  sortOrder: number;
  note?: string | null;
}

export interface PostAdminGameRequest {
  raGameId: number;
}

export interface GameOfTheWeekRaGameIdRequest {
  raGameId: number;
}

export interface PostGameOfTheWeekPollRequest {
  startsAt: string;
  endsAt: string;
  raGameIds: number[];
}

export interface GameOfTheWeekBallotItemDto {
  raGameId: number;
  title: string;
  consoleName?: string | null;
  imageIcon?: string | null;
  sortOrder: number;
  isTracked: boolean;
  voteCount: number;
  addedByMemberId?: string | null;
}

export interface GameOfTheWeekCurrentPollDto {
  pollId: string;
  phase: number;
  startsAt: string;
  endsAt: string;
  closedAt?: string | null;
  winnerRaGameId?: number | null;
  trackingStatus: number;
  myVoteRaGameId?: number | null;
  ballot: GameOfTheWeekBallotItemDto[];
  ballotSlotsRemaining: number;
}

export interface PatchAdminGameLeaderboardSyncRequest {
  forceColdLeaderboardSync: boolean;
}

export interface DashboardResponse {
  championship: ChampionshipRowDto[];
  recentGroupGames: RecentGroupGameDto[];
}

export interface DashboardGamesResponse {
  total: number;
  offset: number;
  limit: number;
  items: DashboardGameDto[];
}

export interface DashboardAchievementActivityItemDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  raGameId: number;
  gameTitle: string;
  raAchievementId: number;
  title: string;
  points: number;
  badgeUrl?: string | null;
  dateEarned?: string | null;
  hardcoreEarned: boolean;
}

export interface DashboardAchievementActivityResponse {
  total: number;
  offset: number;
  limit: number;
  items: DashboardAchievementActivityItemDto[];
}

export interface DashboardAchievementTopGameDto {
  raGameId: number;
  title: string;
  unlockCount: number;
}

export interface DashboardAchievementSummaryResponse {
  unlocksLast7Days: number;
  unlocksLast30Days: number;
  activeMembersLast7Days: number;
  lastUnlockAt?: string | null;
  topGameLast7Days?: DashboardAchievementTopGameDto | null;
  achievementsSyncedAt?: string | null;
}

export interface DashboardAchievementHistoryItemDto {
  earnedAt: string;
  cumulativeUnlocks: number;
  cumulativePoints: number;
  cumulativeTruePoints: number;
}

export interface DashboardAchievementHistoryResponse {
  items: DashboardAchievementHistoryItemDto[];
}

export interface GameAchievementMemberDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
}

export interface GameAchievementCatalogItemDto {
  raAchievementId: number;
  title: string;
  description?: string | null;
  points: number;
  trueRatio: number;
  badgeUrl?: string | null;
  displayOrder: number;
}

export interface GameAchievementMemberUnlockDto {
  memberId: string;
  raAchievementId: number;
  dateEarned?: string | null;
  hardcoreEarned: boolean;
}

export interface GameAchievementMemberSummaryDto {
  memberId: string;
  achievementsEarned: number;
  achievementsTotal: number;
  pointsEarned: number;
  pointsPossible: number;
  lastUnlockAt?: string | null;
}

export interface GameAchievementRecentUnlockDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  raAchievementId: number;
  title: string;
  points: number;
  badgeUrl?: string | null;
  dateEarned?: string | null;
  hardcoreEarned: boolean;
}

export interface GameAchievementsResponse {
  raGameId: number;
  title: string;
  achievementProgressSyncedAt?: string | null;
  achievements: GameAchievementCatalogItemDto[];
  members: GameAchievementMemberDto[];
  unlocks: GameAchievementMemberUnlockDto[];
  memberSummaries: GameAchievementMemberSummaryDto[];
  completionLeader?: unknown | null;
  membersMastered: number;
  recentUnlocks: GameAchievementRecentUnlockDto[];
}

export interface AchievementDistributionBucketDto {
  achievementsEarned: number;
  playerCount: number;
}

export interface GameAchievementDistributionResponse {
  raGameId: number;
  available: boolean;
  syncedAt?: string | null;
  softcoreBuckets: AchievementDistributionBucketDto[];
  hardcoreBuckets: AchievementDistributionBucketDto[];
}

export interface MemberAchievementListItemDto {
  raAchievementId: number;
  raGameId: number;
  gameTitle: string;
  isTracked: boolean;
  title: string;
  description?: string | null;
  points: number;
  badgeUrl?: string | null;
  dateEarned?: string | null;
  hardcoreEarned: boolean;
}

export interface MemberAchievementsListResponse {
  total: number;
  offset: number;
  limit: number;
  items: MemberAchievementListItemDto[];
  achievementsProgressSyncedAt?: string | null;
}

export interface MemberSummaryDto {
  id: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
}

export interface RivalryBoardDto {
  raLeaderboardId: number;
  title: string;
  raGameId: number;
  gameTitle: string;
  memberAScore?: number | null;
  memberAFormattedScore?: string | null;
  memberAFriendRank?: number | null;
  memberAGlobalRank?: number | null;
  memberBScore?: number | null;
  memberBFormattedScore?: string | null;
  memberBFriendRank?: number | null;
  memberBGlobalRank?: number | null;
  globalEntryCount?: number | null;
  leaderUsername?: string | null;
}

export interface RivalryGameDto {
  raGameId: number;
  gameTitle: string;
  boards: RivalryBoardDto[];
}

export interface RivalryResponse {
  memberA: MemberSummaryDto;
  memberB: MemberSummaryDto;
  memberALeads: number;
  memberBLeads: number;
  tiedBoards: number;
  games: RivalryGameDto[];
}

export interface AdminLastSyncByKindDto {
  kind: string;
  status?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
}

export interface AdminOpsDto {
  health: AdminOpsHealthDto;
  lastSyncByKind: AdminLastSyncByKindDto[];
  recentRuns: AdminSyncRunDto[];
  memberCoverageSummary: AdminMemberCoverageSummaryDto;
  members: AdminMemberCoverageDto[];
  scheduler: AdminSchedulerDto;
  config: AdminOpsConfigDto;
}

export interface AdminOpsHealthDto {
  overallStatus: string;
  leaderboardSyncInProgress: boolean;
  lastSuccessfulLeaderboardSyncAt?: string | null;
  intervalMinutes: number;
  estimatedNextScheduledSyncAt?: string | null;
  manualCooldownUntil?: string | null;
}

export interface AdminSyncRunDto {
  id: string;
  kind: string;
  trigger: string;
  status: string;
  startedAt: string;
  finishedAt?: string | null;
  error?: string | null;
  raGameId?: number | null;
  gameTitle?: string | null;
  memberDisplayName?: string | null;
}

export interface AdminMemberCoverageSummaryDto {
  membersWithApiKey: number;
  totalMembers: number;
}

export interface AdminMemberCoverageDto {
  raUsername: string;
  displayName: string;
  hasApiKey: boolean;
  boardsWithScore: number;
  lastEntrySyncedAt?: string | null;
}

export interface AdminSchedulerDto {
  recurringJobs: RecurringJobSnapshotDto[];
}

export interface RecurringJobSnapshotDto {
  jobId: string;
  cron?: string | null;
  lastExecution?: string | null;
  nextExecution?: string | null;
  lastJobState?: string | null;
  configuredIntervalMinutes?: number | null;
  configuredIntervalDays?: number | null;
}

export interface DiscordNotificationEventKind {
}

export interface AdminDiscordWebhookSummaryDto {
  id: string;
  name: string;
  enabled: boolean;
  webhookUrlMasked: string;
  digestIntervalMinutes: number;
  eventKinds: string[];
  updatedAt: string;
}

export interface AdminDiscordWebhookDetailDto {
  id: string;
  name: string;
  enabled: boolean;
  webhookUrlMasked: string;
  digestIntervalMinutes: number;
  payloadTemplateJson: string;
  eventKinds: string[];
  allowedRaGameIds?: number[] | null;
  updatedAt: string;
}

export interface UpsertDiscordWebhookRequest {
  name: string;
  enabled: boolean;
  webhookUrl: string;
  digestIntervalMinutes: number;
  payloadTemplateJson: string;
  eventKinds: string[];
  allowedRaGameIds?: number[] | null;
}

export interface DiscordTokenCatalogDto {
  events: DiscordTokenCatalogEntryDto[];
}

export interface DiscordTokenCatalogEntryDto {
  eventKind: string;
  tokens: DiscordTokenCatalogTokenDto[];
}

export interface DiscordTokenCatalogTokenDto {
  code: string;
  label: string;
}

export interface PreviewDiscordWebhookRequest {
  eventKind: string;
  payloadTemplateJson?: string | null;
}

export interface PreviewDiscordWebhookResponse {
  renderedPayloadJson: string;
}

export interface TestDiscordWebhookRequest {
  eventKind: string;
}

export interface AdminNotificationDispatchRunDto {
  id: string;
  status: string;
  startedAt: string;
  finishedAt?: string | null;
  error?: string | null;
  eventsProcessed: number;
  postsSucceeded: number;
  postsFailed: number;
}

export interface AdminSyncSettingsDto {
  leaderboard: AdminLeaderboardSyncSettingsDto;
  recurringJobs: AdminRecurringJobSettingsDto[];
}

export interface AdminLeaderboardSyncSettingsDto {
  hotIntervalMinutes: number;
  coldIntervalMinutes: number;
  hotActivityWindowHours: number;
}

export interface AdminRecurringJobSettingsDto {
  jobId: string;
  displayName: string;
  intervalMinutes?: number | null;
  intervalDays?: number | null;
}

export interface PatchAdminSyncSettingsRequest {
  leaderboard?: PatchLeaderboardSyncSettingsRequest;
  recurringJobs?: PatchRecurringJobSettingsRequest[];
}

export interface PatchLeaderboardSyncSettingsRequest {
  hotIntervalMinutes: number;
  coldIntervalMinutes: number;
  hotActivityWindowHours: number;
}

export interface PatchRecurringJobSettingsRequest {
  jobId: string;
  intervalMinutes?: number | null;
  intervalDays?: number | null;
}

export interface AdminOpsConfigDto {
  sharedCatalogKeyConfigured: boolean;
  distinctMemberApiKeys: number;
  keysInPool: number;
  hangfireDashboardUrl: string;
}

export type ApiClientOptions = {
  baseUrl: string;
  fetch?: typeof fetch;
};

async function request<T>(baseUrl: string, path: string, init?: RequestInit, fetchImpl: typeof fetch = fetch): Promise<T> {
  const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}${path}`, {
    ...init,
    headers: {
      Accept: "application/json",
      ...(init?.headers ?? {}),
    },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`API ${response.status}: ${body || response.statusText}`);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}

export function createApiClient(options: ApiClientOptions) {
  const fetchImpl = options.fetch ?? fetch;
  const baseUrl = options.baseUrl;

  return {
    getDashboard: () => request<DashboardResponse>(baseUrl, "/api/dashboard", undefined, fetchImpl),
    getDashboardGames: (limit?: number, offset?: number, sort?: string, q?: string) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      if (sort) params.set("sort", sort);
      if (q) params.set("q", q);
      const qs = params.toString();
      return request<DashboardGamesResponse>(
        baseUrl,
        `/api/dashboard/games${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getDashboardAchievementActivity: (limit?: number, offset?: number, raGameId?: number, raUsername?: string) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      if (raGameId != null) params.set("raGameId", String(raGameId));
      if (raUsername) params.set("raUsername", raUsername);
      const qs = params.toString();
      return request<DashboardAchievementActivityResponse>(
        baseUrl,
        `/api/dashboard/achievement-activity${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getDashboardAchievementSummary: () =>
      request<DashboardAchievementSummaryResponse>(
        baseUrl,
        "/api/dashboard/achievement-summary",
        undefined,
        fetchImpl,
      ),
    getDashboardAchievementHistory: (limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<DashboardAchievementHistoryResponse>(
        baseUrl,
        `/api/dashboard/achievement-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getRivalry: (usernameA: string, usernameB: string) =>
      request<RivalryResponse>(
        baseUrl,
        `/api/rivalry/${encodeURIComponent(usernameA)}/${encodeURIComponent(usernameB)}`,
        undefined,
        fetchImpl,
      ),
    getMembers: () => request<MemberDto[]>(baseUrl, "/api/members", undefined, fetchImpl),
    getMembersSummary: () =>
      request<MembersSummaryDto>(baseUrl, "/api/members/summary", undefined, fetchImpl),
    getCurrentMember: () => request<CurrentMemberDto>(baseUrl, "/api/members/me", undefined, fetchImpl),
    getMemberSelfSyncStatus: () =>
      request<MemberSelfSyncStatusDto>(baseUrl, "/api/members/me/sync-status", undefined, fetchImpl),
    postMemberSelfSyncLeaderboards: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/members/me/sync/leaderboards`, {
        method: "POST",
      });
      if (!response.ok) {
        const body = await response.text();
        throw new Error(`API ${response.status}: ${body || response.statusText}`);
      }
      return (await response.json()) as MemberSelfSyncLeaderboardsResponse;
    },
    postMemberSelfSyncProfile: () =>
      request<MemberSelfSyncRunResponse>(baseUrl, "/api/members/me/sync/profile", { method: "POST" }, fetchImpl),
    postMemberSelfSyncAchievements: () =>
      request<MemberSelfSyncRunResponse>(baseUrl, "/api/members/me/sync/achievements", { method: "POST" }, fetchImpl),
    putMemberRaAccount: (raUsername: string, raApiKey: string) =>
      request<void>(baseUrl, "/api/members/me/ra-account", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raUsername, raApiKey }),
      }, fetchImpl),
    putMemberApiKey: (raApiKey: string) =>
      request<void>(baseUrl, "/api/members/me/api-key", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raApiKey }),
      }, fetchImpl),
    putMemberProfile: (avatarUrl: string | null) =>
      request<void>(baseUrl, "/api/members/me/profile", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ avatarUrl }),
      }, fetchImpl),
    getMember: (raUsername: string) =>
      request<MemberDetailDto>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}`,
        undefined,
        fetchImpl,
      ),
    getMemberRaSummary: (raUsername: string) =>
      request<MemberRaSummaryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/ra-summary`,
        undefined,
        fetchImpl,
      ),
    getMemberRaRankHistory: (raUsername: string, limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<MemberRaRankHistoryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/ra-rank-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getMemberRaAchievementHistory: (
      raUsername: string,
      limit?: number,
      trackedOnly?: boolean,
      raGameId?: number,
    ) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (trackedOnly) params.set("trackedOnly", "true");
      if (raGameId != null) params.set("raGameId", String(raGameId));
      const qs = params.toString();
      return request<MemberRaAchievementHistoryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/ra-achievement-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getMemberAchievements: (
      raUsername: string,
      limit?: number,
      offset?: number,
      trackedOnly?: boolean,
    ) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      if (trackedOnly) params.set("trackedOnly", "true");
      const qs = params.toString();
      return request<MemberAchievementsListResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/achievements${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getMemberHistory: (raUsername: string, limit?: number, offset?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      const qs = params.toString();
      return request<MemberHistoryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getGames: () => request<GameDto[]>(baseUrl, "/api/games", undefined, fetchImpl),
    getGameSources: (raGameId: number) =>
      request<GameSourceDto[]>(baseUrl, `/api/games/${raGameId}/sources`, undefined, fetchImpl),
    getGameLeaderboards: (raGameId: number) =>
      request<GameLeaderboardsResponse>(baseUrl, `/api/games/${raGameId}/leaderboards`, undefined, fetchImpl),
    postGameRefresh: async (raGameId: number) => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/games/${raGameId}/refresh`, {
        method: "POST",
      });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getGameHistory: (raGameId: number, limit?: number, offset?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      const qs = params.toString();
      return request<GameHistoryResponse>(
        baseUrl,
        `/api/games/${raGameId}/history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getGameAchievements: (raGameId: number) =>
      request<GameAchievementsResponse>(baseUrl, `/api/games/${raGameId}/achievements`, undefined, fetchImpl),
    getGameAchievementDistribution: (raGameId: number) =>
      request<GameAchievementDistributionResponse>(
        baseUrl,
        `/api/games/${raGameId}/achievement-distribution`,
        undefined,
        fetchImpl,
      ),
    getGameLeaderboardPopulationHistory: (raGameId: number, limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<GameLeaderboardPopulationHistoryResponse>(
        baseUrl,
        `/api/games/${raGameId}/leaderboard-population-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getLeaderboard: (raLeaderboardId: number) =>
      request<LeaderboardDetailDto>(baseUrl, `/api/leaderboards/${raLeaderboardId}`, undefined, fetchImpl),
    getLeaderboardHistory: (raLeaderboardId: number, limit?: number, offset?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      const qs = params.toString();
      return request<LeaderboardHistoryResponse>(
        baseUrl,
        `/api/leaderboards/${raLeaderboardId}/history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    triggerSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync`, { method: "POST" });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getSyncStatus: () => request<SyncStatusDto>(baseUrl, "/api/sync/status", undefined, fetchImpl),
    triggerMetadataSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/metadata`, { method: "POST" });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getMetadataSyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/metadata/status", undefined, fetchImpl),
    triggerConsoleIconSync: async (force = false) => {
      const qs = force ? "?force=true" : "";
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/console-icons${qs}`, {
        method: "POST",
      });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getConsoleIconSyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/console-icons/status", undefined, fetchImpl),
    triggerDueDispatchSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/dispatch`, { method: "POST" });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    triggerMemberActivitySync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/member-activity`, {
        method: "POST",
      });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getMemberActivitySyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/member-activity/status", undefined, fetchImpl),
    triggerMemberRankSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/member-rank`, { method: "POST" });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getMemberRankSyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/member-rank/status", undefined, fetchImpl),
    triggerMemberAchievementSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/member-achievements`, {
        method: "POST",
      });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getMemberAchievementSyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/member-achievements/status", undefined, fetchImpl),
    getAdminOps: () => request<AdminOpsDto>(baseUrl, "/api/admin/ops", undefined, fetchImpl),
    getAdminSyncSettings: () =>
      request<AdminSyncSettingsDto>(baseUrl, "/api/admin/sync-settings", undefined, fetchImpl),
    patchAdminSyncSettings: (body: PatchAdminSyncSettingsRequest) =>
      request<AdminSyncSettingsDto>(baseUrl, "/api/admin/sync-settings", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    getAdminGames: () => request<AdminGameDto[]>(baseUrl, "/api/admin/games", undefined, fetchImpl),
    getGameOfTheWeekCurrent: () =>
      request<GameOfTheWeekCurrentPollDto>(baseUrl, "/api/game-of-the-week/current", undefined, fetchImpl),
    postGameOfTheWeekBallot: (raGameId: number) =>
      request<GameOfTheWeekCurrentPollDto>(baseUrl, "/api/game-of-the-week/current/ballot", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raGameId }),
      }, fetchImpl),
    putGameOfTheWeekVote: (raGameId: number) =>
      request<GameOfTheWeekCurrentPollDto>(baseUrl, "/api/game-of-the-week/current/vote", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raGameId }),
      }, fetchImpl),
    postAdminGameOfTheWeekPoll: (body: PostGameOfTheWeekPollRequest) =>
      request<GameOfTheWeekCurrentPollDto>(baseUrl, "/api/admin/game-of-the-week/polls", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    getAdminGameOfTheWeekCurrentPoll: () =>
      request<GameOfTheWeekCurrentPollDto>(
        baseUrl,
        "/api/admin/game-of-the-week/polls/current",
        undefined,
        fetchImpl,
      ),
    getAdminGameTrackQueue: () =>
      request<AdminGameTrackQueueItemDto[]>(baseUrl, "/api/admin/game-track-queue", undefined, fetchImpl),
    postAdminGameTrackQueueReject: (id: string) =>
      request<AdminGameTrackQueueItemDto>(
        baseUrl,
        `/api/admin/game-track-queue/${id}/reject`,
        { method: "POST" },
        fetchImpl,
      ),
    postAdminGame: (raGameId: number) =>
      request<AdminGameDto>(baseUrl, "/api/admin/games", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raGameId }),
      }, fetchImpl),
    deleteAdminGame: (raGameId: number) =>
      request<void>(baseUrl, `/api/admin/games/${raGameId}`, { method: "DELETE" }, fetchImpl),
    postAdminGameRefresh: (raGameId: number) =>
      request<AdminGameDto>(baseUrl, `/api/admin/games/${raGameId}/refresh`, { method: "POST" }, fetchImpl),
    patchAdminGameLeaderboardSync: (raGameId: number, forceColdLeaderboardSync: boolean) =>
      request<AdminGameDto>(baseUrl, `/api/admin/games/${raGameId}/leaderboard-sync`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ forceColdLeaderboardSync }),
      }, fetchImpl),
    getAdminGameSources: (raGameId: number) =>
      request<GameSourceDto[]>(baseUrl, `/api/admin/games/${raGameId}/sources`, undefined, fetchImpl),
    postAdminGameSource: (raGameId: number, body: UpsertGameSourceRequest) =>
      request<GameSourceDto>(baseUrl, `/api/admin/games/${raGameId}/sources`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    putAdminGameSource: (raGameId: number, sourceId: string, body: UpsertGameSourceRequest) =>
      request<GameSourceDto>(baseUrl, `/api/admin/games/${raGameId}/sources/${sourceId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    deleteAdminGameSource: (raGameId: number, sourceId: string) =>
      request<void>(
        baseUrl,
        `/api/admin/games/${raGameId}/sources/${sourceId}`,
        { method: "DELETE" },
        fetchImpl,
      ),
    getAdminMemberInvites: () =>
      request<AdminMemberInviteDto[]>(baseUrl, "/api/admin/member-invites", undefined, fetchImpl),
    postAdminMemberInvite: (discordId: string) =>
      request<AdminMemberInviteDto>(baseUrl, "/api/admin/member-invites", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ discordId }),
      }, fetchImpl),
    deleteAdminMemberInvite: (discordId: string) =>
      request<void>(
        baseUrl,
        `/api/admin/member-invites/${encodeURIComponent(discordId)}`,
        { method: "DELETE" },
        fetchImpl,
      ),
    patchAdminMemberIsAdmin: (discordId: string, isAdmin: boolean) =>
      request<void>(
        baseUrl,
        `/api/admin/member-invites/${encodeURIComponent(discordId)}/is-admin`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ isAdmin }),
        },
        fetchImpl,
      ),
    getAdminDiscordWebhookTokenCatalog: () =>
      request<DiscordTokenCatalogDto>(baseUrl, "/api/admin/discord-webhooks/token-catalog", undefined, fetchImpl),
    getAdminDiscordWebhookDispatchRuns: (limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<AdminNotificationDispatchRunDto[]>(
        baseUrl,
        `/api/admin/discord-webhooks/dispatch-runs${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getAdminDiscordWebhooks: () =>
      request<AdminDiscordWebhookSummaryDto[]>(baseUrl, "/api/admin/discord-webhooks", undefined, fetchImpl),
    getAdminDiscordWebhook: (id: string) =>
      request<AdminDiscordWebhookDetailDto>(baseUrl, `/api/admin/discord-webhooks/${id}`, undefined, fetchImpl),
    postAdminDiscordWebhook: (body: UpsertDiscordWebhookRequest) =>
      request<AdminDiscordWebhookDetailDto>(baseUrl, "/api/admin/discord-webhooks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    putAdminDiscordWebhook: (id: string, body: UpsertDiscordWebhookRequest) =>
      request<AdminDiscordWebhookDetailDto>(baseUrl, `/api/admin/discord-webhooks/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    deleteAdminDiscordWebhook: (id: string) =>
      request<void>(baseUrl, `/api/admin/discord-webhooks/${id}`, { method: "DELETE" }, fetchImpl),
    postAdminDiscordWebhookPreview: (id: string, body: PreviewDiscordWebhookRequest) =>
      request<PreviewDiscordWebhookResponse>(baseUrl, `/api/admin/discord-webhooks/${id}/preview`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    postAdminDiscordWebhookTest: (id: string, body: TestDiscordWebhookRequest) =>
      request<void>(baseUrl, `/api/admin/discord-webhooks/${id}/test`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
