/* Generated by scripts/generate-api-client.mjs — do not hand-edit types lightly. */
export interface AddGameRequest {
  raGameId: number;
}

export interface PutMemberApiKeyRequest {
  raApiKey: string;
}

export interface PutMemberProfileRequest {
  avatarUrl?: string | null;
}

export interface CurrentMemberDto {
  id: string;
  raUsername?: string | null;
  raUlid?: string | null;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
  hasApiKey: boolean;
  needsOnboarding: boolean;
  isAdmin: boolean;
}

export interface PutMemberRaAccountRequest {
  raUsername: string;
  raApiKey: string;
}

export interface PostAdminMemberInviteRequest {
  discordId: string;
}

export interface PatchAdminMemberIsAdminRequest {
  isAdmin: boolean;
}

export interface AdminMemberInviteDto {
  discordId: string;
  displayName?: string | null;
  hasRaAccount: boolean;
  hasApiKey: boolean;
  isAdmin: boolean;
}

export interface MemberDto {
  id: string;
  raUsername?: string | null;
  raUlid?: string | null;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
  hasApiKey?: boolean;
}

export interface MemberStandingDto {
  raGameId: number;
  gameTitle: string;
  raLeaderboardId: number;
  leaderboardTitle: string;
  format?: string | null;
  friendRank?: number | null;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  score: number;
  formattedScore: string;
}

export interface MemberRaRankHistoryResponse {
  items: MemberRaRankHistoryItemDto[];
}

export interface MemberRaRankHistoryItemDto {
  syncedAt: string;
  rank?: number | null;
  totalRanked?: number | null;
  totalPoints?: number | null;
  totalTruePoints?: number | null;
  totalSoftcorePoints?: number | null;
}

export interface MemberRaAchievementHistoryResponse {
  items: MemberRaAchievementHistoryItemDto[];
}

export interface MemberRaAchievementHistoryItemDto {
  earnedAt: string;
  cumulativeUnlocks: number;
  cumulativePoints: number;
  cumulativeTruePoints: number;
}

export interface MemberRaUnlockedAchievementDto {
  raAchievementId: number;
  title: string;
  description?: string | null;
  points: number;
  badgeUrl?: string | null;
  dateEarned?: string | null;
  hardcoreAchieved: boolean;
}

export interface MemberRaSummaryResponse {
  available: boolean;
  unavailableReason?: string | null;
  summary?: MemberRaSummaryDto | null;
}

export interface MemberRaSummaryDto {
  raUsername: string;
  raUlid?: string | null;
  motto?: string | null;
  userPicUrl?: string | null;
  memberSince?: string | null;
  status?: string | null;
  rank?: number | null;
  totalRanked?: number | null;
  totalPoints?: number | null;
  totalSoftcorePoints?: number | null;
  totalTruePoints?: number | null;
  presence?: MemberRaPresenceGameDto | null;
  recentlyPlayed: MemberRaRecentGameDto[];
  recentAchievements: MemberRaRecentAchievementDto[];
}

export interface MemberRaPresenceGameDto {
  raGameId: number;
  title: string;
  consoleId: number;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  isTracked: boolean;
  richPresenceMsg?: string | null;
  richPresenceAt?: string | null;
  progress?: MemberRaGameProgressDto | null;
  unlockedAchievements: MemberRaUnlockedAchievementDto[];
}

export interface MemberRaRecentGameDto {
  raGameId: number;
  title: string;
  consoleId: number;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  isTracked: boolean;
  lastPlayedAt?: string | null;
  progress?: MemberRaGameProgressDto | null;
  unlockedAchievements: MemberRaUnlockedAchievementDto[];
}

export interface MemberRaGameProgressDto {
  achievementsEarned: number;
  achievementsTotal: number;
  pointsEarned: number;
  pointsPossible?: number | null;
  achievementsEarnedHardcore?: number | null;
  pointsEarnedHardcore?: number | null;
}

export interface MemberRaRecentAchievementDto {
  raAchievementId: number;
  raGameId: number;
  gameTitle: string;
  title: string;
  description?: string | null;
  points: number;
  badgeUrl?: string | null;
  dateAwarded?: string | null;
  hardcoreAchieved: boolean;
  isTracked: boolean;
}

export interface MemberDetailDto {
  id: string;
  raUsername: string;
  raUlid?: string | null;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
  standings: MemberStandingDto[];
}

export interface MemberHistoryItemDto {
  id: string;
  raGameId: number;
  gameTitle: string;
  raLeaderboardId: number;
  leaderboardTitle: string;
  format?: string | null;
  score: number;
  formattedScore: string;
  globalRank?: number | null;
  friendRank?: number | null;
  syncedAt: string;
}

export interface MemberHistoryResponse {
  total: number;
  offset: number;
  limit: number;
  items: MemberHistoryItemDto[];
}

export interface GameDto {
  id: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  leaderboardCount: number;
}

export interface StandingMemberDto {
  id: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
}

export interface FriendStandingDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  score?: number | null;
  formattedScore?: string | null;
  globalRank?: number | null;
  friendRank?: number | null;
  scoreUpdatedAt?: string | null;
}

export interface GameLeaderboardDto {
  id: string;
  raLeaderboardId: number;
  title: string;
  description?: string | null;
  format?: string | null;
  rankAsc: boolean;
  globalEntryCount?: number | null;
  globalEntryCountSyncedAt?: string | null;
  standings: FriendStandingDto[];
}

export interface GameLeaderboardsResponse {
  gameId: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  publisher?: string | null;
  developer?: string | null;
  genre?: string | null;
  releasedAt?: string | null;
  metadataSyncedAt?: string | null;
  members: StandingMemberDto[];
  leaderboards: GameLeaderboardDto[];
}

export interface GameHistoryItemDto {
  id: string;
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  raLeaderboardId: number;
  leaderboardTitle: string;
  format?: string | null;
  score: number;
  formattedScore: string;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  friendRank?: number | null;
  syncedAt: string;
}

export interface GameHistoryResponse {
  total: number;
  offset: number;
  limit: number;
  items: GameHistoryItemDto[];
}

export interface LeaderboardPopulationPointDto {
  syncedAt: string;
  entryCount: number;
}

export interface LeaderboardPopulationSeriesDto {
  raLeaderboardId: number;
  title: string;
  points: LeaderboardPopulationPointDto[];
}

export interface GameLeaderboardPopulationHistoryResponse {
  boards: LeaderboardPopulationSeriesDto[];
}

export interface LeaderboardDetailDto {
  id: string;
  raLeaderboardId: number;
  raGameId: number;
  gameTitle: string;
  title: string;
  description?: string | null;
  format?: string | null;
  rankAsc: boolean;
  globalEntryCount?: number | null;
  globalEntryCountSyncedAt?: string | null;
  standings: FriendStandingDto[];
}

export interface LeaderboardHistoryItemDto {
  id: string;
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  score: number;
  formattedScore: string;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  friendRank?: number | null;
  syncedAt: string;
}

export interface LeaderboardHistoryResponse {
  total: number;
  offset: number;
  limit: number;
  items: LeaderboardHistoryItemDto[];
}

export interface SyncAcceptedResponse {
  jobId: string;
}

export interface SyncCooldownResponse {
  message: string;
  availableAt?: string | null;
}

export interface SyncStatusDto {
  id?: string | null;
  trigger?: string | null;
  status?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  error?: string | null;
}

export interface ChampionshipRowDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  friendRankOnes: number;
  boardsWithScore: number;
}

export interface ActivityItemDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  raGameId: number;
  gameTitle: string;
  raLeaderboardId: number;
  leaderboardTitle: string;
  scoreDelta?: number | null;
  friendRankDelta?: number | null;
  globalRank?: number | null;
  globalEntryCount?: number | null;
  globalRankDelta?: number | null;
  formattedScore?: string | null;
}

export interface DashboardGameLeaderDto {
  displayName: string;
  raUsername: string;
  avatarUrl?: string | null;
  friendRankOnes: number;
}

export interface DashboardGamePlayerAvatarDto {
  displayName: string;
  raUsername: string;
  avatarUrl: string;
}

export interface DashboardGameDto {
  id: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  leaderboardCount: number;
  maxGlobalEntryCount?: number | null;
  maxGlobalEntryCountLeaderboardTitle?: string | null;
  friendRankOneLeader?: DashboardGameLeaderDto | null;
  playersWithAvatars: DashboardGamePlayerAvatarDto[];
  lastActivityAt?: string | null;
}

export interface RecentGroupGamePlayerDto {
  memberId: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  lastPlayedAt: string;
}

export interface RecentGroupGameDto {
  raGameId: number;
  title: string;
  consoleId: number;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  lastPlayedAt: string;
  isTracked: boolean;
  players: RecentGroupGamePlayerDto[];
}

export interface AdminGameTrackQueueItemDto {
  id: string;
  raGameId: number;
  status: number;
  title: string;
  consoleName?: string | null;
  enqueuedAt: string;
  resolvedAt?: string | null;
  failureMessage?: string | null;
}

export interface AdminGameDto {
  id: string;
  raGameId: number;
  title: string;
  consoleName?: string | null;
  consoleIconUrl?: string | null;
  imageBoxArtUrl?: string | null;
  imageIconUrl?: string | null;
  imageTitleUrl?: string | null;
  imageIngameUrl?: string | null;
  leaderboardCount: number;
  sourceCount: number;
  metadataSyncedAt?: string | null;
}

export interface GameSourceDto {
  id: string;
  sourceType: string;
  url: string;
  label?: string | null;
  sortOrder: number;
  note?: string | null;
}

export interface UpsertGameSourceRequest {
  sourceType: string;
  url: string;
  label?: string | null;
  sortOrder: number;
  note?: string | null;
}

export interface PostAdminGameRequest {
  raGameId: number;
}

export interface DashboardResponse {
  championship: ChampionshipRowDto[];
  recentGroupGames: RecentGroupGameDto[];
  games: DashboardGameDto[];
}

export interface MemberSummaryDto {
  id: string;
  raUsername: string;
  displayName: string;
  avatarUrl?: string | null;
  boardsWithScore: number;
  friendRankOnes: number;
}

export interface RivalryBoardDto {
  raLeaderboardId: number;
  title: string;
  raGameId: number;
  gameTitle: string;
  memberAScore?: number | null;
  memberAFormattedScore?: string | null;
  memberAFriendRank?: number | null;
  memberAGlobalRank?: number | null;
  memberBScore?: number | null;
  memberBFormattedScore?: string | null;
  memberBFriendRank?: number | null;
  memberBGlobalRank?: number | null;
  globalEntryCount?: number | null;
  leaderUsername?: string | null;
}

export interface RivalryGameDto {
  raGameId: number;
  gameTitle: string;
  boards: RivalryBoardDto[];
}

export interface RivalryResponse {
  memberA: MemberSummaryDto;
  memberB: MemberSummaryDto;
  memberALeads: number;
  memberBLeads: number;
  tiedBoards: number;
  games: RivalryGameDto[];
}

export interface AdminOpsDto {
  health: AdminOpsHealthDto;
  recentRuns: AdminSyncRunDto[];
  memberCoverageSummary: AdminMemberCoverageSummaryDto;
  members: AdminMemberCoverageDto[];
  scheduler: AdminSchedulerDto;
  config: AdminOpsConfigDto;
}

export interface AdminOpsHealthDto {
  overallStatus: string;
  leaderboardSyncInProgress: boolean;
  lastSuccessfulLeaderboardSyncAt?: string | null;
  intervalMinutes: number;
  estimatedNextScheduledSyncAt?: string | null;
  manualCooldownUntil?: string | null;
}

export interface AdminSyncRunDto {
  id: string;
  kind: string;
  trigger: string;
  status: string;
  startedAt: string;
  finishedAt?: string | null;
  error?: string | null;
}

export interface AdminMemberCoverageSummaryDto {
  membersWithApiKey: number;
  totalMembers: number;
}

export interface AdminMemberCoverageDto {
  raUsername: string;
  displayName: string;
  hasApiKey: boolean;
  boardsWithScore: number;
  lastEntrySyncedAt?: string | null;
}

export interface AdminSchedulerDto {
  recurringJobs: RecurringJobSnapshotDto[];
}

export interface RecurringJobSnapshotDto {
  jobId: string;
  cron?: string | null;
  lastExecution?: string | null;
  nextExecution?: string | null;
  lastJobState?: string | null;
}

export interface AdminOpsConfigDto {
  sharedCatalogKeyConfigured: boolean;
  distinctMemberApiKeys: number;
  keysInPool: number;
  hangfireDashboardUrl: string;
}

export type ApiClientOptions = {
  baseUrl: string;
  fetch?: typeof fetch;
};

async function request<T>(baseUrl: string, path: string, init?: RequestInit, fetchImpl: typeof fetch = fetch): Promise<T> {
  const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}${path}`, {
    ...init,
    headers: {
      Accept: "application/json",
      ...(init?.headers ?? {}),
    },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`API ${response.status}: ${body || response.statusText}`);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}

export function createApiClient(options: ApiClientOptions) {
  const fetchImpl = options.fetch ?? fetch;
  const baseUrl = options.baseUrl;

  return {
    getDashboard: () => request<DashboardResponse>(baseUrl, "/api/dashboard", undefined, fetchImpl),
    getRivalry: (usernameA: string, usernameB: string) =>
      request<RivalryResponse>(
        baseUrl,
        `/api/rivalry/${encodeURIComponent(usernameA)}/${encodeURIComponent(usernameB)}`,
        undefined,
        fetchImpl,
      ),
    getMembers: () => request<MemberDto[]>(baseUrl, "/api/members", undefined, fetchImpl),
    getCurrentMember: () => request<CurrentMemberDto>(baseUrl, "/api/members/me", undefined, fetchImpl),
    putMemberRaAccount: (raUsername: string, raApiKey: string) =>
      request<void>(baseUrl, "/api/members/me/ra-account", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raUsername, raApiKey }),
      }, fetchImpl),
    putMemberApiKey: (raApiKey: string) =>
      request<void>(baseUrl, "/api/members/me/api-key", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raApiKey }),
      }, fetchImpl),
    putMemberProfile: (avatarUrl: string | null) =>
      request<void>(baseUrl, "/api/members/me/profile", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ avatarUrl }),
      }, fetchImpl),
    getMember: (raUsername: string) =>
      request<MemberDetailDto>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}`,
        undefined,
        fetchImpl,
      ),
    getMemberRaSummary: (raUsername: string) =>
      request<MemberRaSummaryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/ra-summary`,
        undefined,
        fetchImpl,
      ),
    getMemberRaRankHistory: (raUsername: string, limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<MemberRaRankHistoryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/ra-rank-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getMemberRaAchievementHistory: (raUsername: string, limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<MemberRaAchievementHistoryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/ra-achievement-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getMemberHistory: (raUsername: string, limit?: number, offset?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      const qs = params.toString();
      return request<MemberHistoryResponse>(
        baseUrl,
        `/api/members/${encodeURIComponent(raUsername)}/history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getGames: () => request<GameDto[]>(baseUrl, "/api/games", undefined, fetchImpl),
    getGameSources: (raGameId: number) =>
      request<GameSourceDto[]>(baseUrl, `/api/games/${raGameId}/sources`, undefined, fetchImpl),
    getGameLeaderboards: (raGameId: number) =>
      request<GameLeaderboardsResponse>(baseUrl, `/api/games/${raGameId}/leaderboards`, undefined, fetchImpl),
    getGameHistory: (raGameId: number, limit?: number, offset?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      const qs = params.toString();
      return request<GameHistoryResponse>(
        baseUrl,
        `/api/games/${raGameId}/history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getGameLeaderboardPopulationHistory: (raGameId: number, limit?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      const qs = params.toString();
      return request<GameLeaderboardPopulationHistoryResponse>(
        baseUrl,
        `/api/games/${raGameId}/leaderboard-population-history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    getLeaderboard: (raLeaderboardId: number) =>
      request<LeaderboardDetailDto>(baseUrl, `/api/leaderboards/${raLeaderboardId}`, undefined, fetchImpl),
    getLeaderboardHistory: (raLeaderboardId: number, limit?: number, offset?: number) => {
      const params = new URLSearchParams();
      if (limit != null) params.set("limit", String(limit));
      if (offset != null) params.set("offset", String(offset));
      const qs = params.toString();
      return request<LeaderboardHistoryResponse>(
        baseUrl,
        `/api/leaderboards/${raLeaderboardId}/history${qs ? `?${qs}` : ""}`,
        undefined,
        fetchImpl,
      );
    },
    triggerSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync`, { method: "POST" });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getSyncStatus: () => request<SyncStatusDto>(baseUrl, "/api/sync/status", undefined, fetchImpl),
    triggerMetadataSync: async () => {
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/metadata`, { method: "POST" });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getMetadataSyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/metadata/status", undefined, fetchImpl),
    triggerConsoleIconSync: async (force = false) => {
      const qs = force ? "?force=true" : "";
      const response = await fetchImpl(`${baseUrl.replace(/\/$/, "")}/api/sync/console-icons${qs}`, {
        method: "POST",
      });
      const body = await response.json();
      if (response.status === 429) {
        return { ok: false as const, status: 429 as const, body: body as SyncCooldownResponse };
      }
      if (!response.ok) {
        throw new Error(`API ${response.status}`);
      }
      return { ok: true as const, status: 202 as const, body: body as SyncAcceptedResponse };
    },
    getConsoleIconSyncStatus: () =>
      request<SyncStatusDto>(baseUrl, "/api/sync/console-icons/status", undefined, fetchImpl),
    getAdminOps: () => request<AdminOpsDto>(baseUrl, "/api/admin/ops", undefined, fetchImpl),
    getAdminGames: () => request<AdminGameDto[]>(baseUrl, "/api/admin/games", undefined, fetchImpl),
    getAdminGameTrackQueue: () =>
      request<AdminGameTrackQueueItemDto[]>(baseUrl, "/api/admin/game-track-queue", undefined, fetchImpl),
    postAdminGameTrackQueueApprove: (id: string) =>
      request<AdminGameTrackQueueItemDto>(
        baseUrl,
        `/api/admin/game-track-queue/${id}/approve`,
        { method: "POST" },
        fetchImpl,
      ),
    postAdminGameTrackQueueReject: (id: string) =>
      request<AdminGameTrackQueueItemDto>(
        baseUrl,
        `/api/admin/game-track-queue/${id}/reject`,
        { method: "POST" },
        fetchImpl,
      ),
    postAdminGame: (raGameId: number) =>
      request<AdminGameDto>(baseUrl, "/api/admin/games", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ raGameId }),
      }, fetchImpl),
    deleteAdminGame: (raGameId: number) =>
      request<void>(baseUrl, `/api/admin/games/${raGameId}`, { method: "DELETE" }, fetchImpl),
    postAdminGameRefresh: (raGameId: number) =>
      request<AdminGameDto>(baseUrl, `/api/admin/games/${raGameId}/refresh`, { method: "POST" }, fetchImpl),
    getAdminGameSources: (raGameId: number) =>
      request<GameSourceDto[]>(baseUrl, `/api/admin/games/${raGameId}/sources`, undefined, fetchImpl),
    postAdminGameSource: (raGameId: number, body: UpsertGameSourceRequest) =>
      request<GameSourceDto>(baseUrl, `/api/admin/games/${raGameId}/sources`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    putAdminGameSource: (raGameId: number, sourceId: string, body: UpsertGameSourceRequest) =>
      request<GameSourceDto>(baseUrl, `/api/admin/games/${raGameId}/sources/${sourceId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      }, fetchImpl),
    deleteAdminGameSource: (raGameId: number, sourceId: string) =>
      request<void>(
        baseUrl,
        `/api/admin/games/${raGameId}/sources/${sourceId}`,
        { method: "DELETE" },
        fetchImpl,
      ),
    getAdminMemberInvites: () =>
      request<AdminMemberInviteDto[]>(baseUrl, "/api/admin/member-invites", undefined, fetchImpl),
    postAdminMemberInvite: (discordId: string) =>
      request<AdminMemberInviteDto>(baseUrl, "/api/admin/member-invites", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ discordId }),
      }, fetchImpl),
    deleteAdminMemberInvite: (discordId: string) =>
      request<void>(
        baseUrl,
        `/api/admin/member-invites/${encodeURIComponent(discordId)}`,
        { method: "DELETE" },
        fetchImpl,
      ),
    patchAdminMemberIsAdmin: (discordId: string, isAdmin: boolean) =>
      request<void>(
        baseUrl,
        `/api/admin/member-invites/${encodeURIComponent(discordId)}/is-admin`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ isAdmin }),
        },
        fetchImpl,
      ),
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
